pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Add build commands here
                    echo 'Building Hello World project'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Add deployment commands here
                    echo 'Deploying Hello World project'
                }
            }
        }
        stages {
                stage('Checkout') {
                    steps {
                        script {
                            checkout([$class: 'GitSCM', branches: [[name: 'origin/new-aaron-branch']], userRemoteConfigs: [[url: 'https://github.com/aagezai/SpringMvcInterview.git']], extensions: [[$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'path/to/include/*'], [path: 'another/path/to/include/*']]]]])
                        }
                    }
                }
    }
}
